production:
  clients:
    default:
      uri: <%= ENV.fetch("MONGOID_DB_URI") %>
      options:
        server_selection_timeout: 5

development:
  clients:
    default:
      uri: <%= ENV.fetch("MONGOID_DB_URI") %>
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      uri: <%= ENV.fetch("TEST_MONGOID_DB_URI") %>
      options:
        server_selection_timeout: 5
