production:
  sessions:
    default:
      uri: <%= ENV.fetch("MONGOID_DB_URI") %>
      options:
        server_selection_timeout: 5

development:
  clients:
    default:
      uri: <%= ENV.fetch("MONGOID_DB_URI") %>
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: backend_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
