development:
  clients:
    default:
      uri: mongodb+srv://anclark686:kIYbiUn1iIpciKit@reyaly-finances.o0uz8bc.mongodb.net/reyaly-finances?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5
        # auth_mech: :mongodb_cr

test:
  clients:
    default:
      database: backend_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
